[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "10"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/blockchain-for-financial-inclusion/"
  to = "https://mintblue.com/blockchain-for-financial-inclusion/"
  status = 301
  force = true

[[redirects]]
  from = "/blockchain-for-energy/"
  to = "https://mintblue.com/blockchain-for-energy/"
  status = 301
  force = true

[[redirects]]
  from = "/csrd/"
  to = "https://mintblue.com/csrd/"
  status = 301
  force = true
  
  [[redirects]]
  from = "/esg-solutions/"
  to = "https://mintblue.com/esg-solutions/"
  status = 301
  force = true

  [[redirects]]
  from = "/food-provenance/"
  to = "https://mintblue.com/food-provenance/"
  status = 301
  force = true

  [[redirects]]
  from = "/blockchain-for-social-good/"
  to = "https://mintblue.com/blockchain-for-good/"
  status = 301
  force = true

  [[redirects]]
  from = "/blockchain-for-charities/"
  to = "https://mintblue.com/blockchain-for-ngos/"
  status = 301
  force = true

  [[redirects]]
  from = "/data-ownership/"
  to = "https://mintblue.com/data-ownership/"
  status = 301
  force = true

  
