[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "10"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/data-interoperability/"
  to = "https://mintblue.com/data-interoperability/"
  status = 301
  force = true

[[redirects]]
  from = "/data-ownership/"
  to = "https://mintblue.com/data-ownership/"
  status = 301
  force = true

[[redirects]]
  from = "/data-sovereignty/"
  to = "https://mintblue.com/data-sovereignty/"
  status = 301
  force = true


  [[redirects]]
    from = "/data-governance-principles/"
    to = "https://mintblue.com/data-governance/"
    status = 301
    force = true

  [[redirects]]
    from = "/data-governance-act/"
    to = "https://mintblue.com/data-governance/"
    status = 301
    force = true

  [[redirects]]
    from = "/digital-identity-solutions/"
    to = "https://mintblue.com/blockchain-identity-authentication/"
    status = 301
    force = true
