[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "10"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/blockchain-for-financial-inclusion/"
  to = "https://mintblue.com/blockchain-for-financial-inclusion/"
  status = 301
  force = true

