[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "10"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/data-interoperability/"
  to = "https://mintblue.com/data-interoperability/"
  status = 301
  force = true
